name: reliquary_fe
description: "Frontend for the Reliquary cold storage system."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  file_picker: ^8.1.7
  flutter_appauth: ^12.0.0
  mime: ^2.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk.ttf
          weight: 700
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700
